-- Create the waitlist table
create table public.waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text
);

-- Create the contact_form table
create table public.contact_form (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  role text,
  message text not null
);

-- Enable Row Level Security (RLS) is recommended, but for now ensure the anon key has insert access.
-- If you enable RLS, you will need policies like:
-- alter table public.waitlist enable row level security;
-- create policy "Enable insert for anon" on public.waitlist for insert with check (true);
